[package]
name = "vector_bin_packing"
version = "0.1.0"
authors = ["Ryan P. Brewster <RyanPBrewster@gmail.com>"]

[dependencies]
num = "0.1.40"
rand = "0.3.16"
structopt = "0.1.0"
structopt-derive = "0.1.0"

